language: python

sudo: required

before_install:
  - sudo apt update
  - sudo apt install libgsl0-dev gcc python3 python3-pip python3-dev python3-setuptools

install:
  - sudo pip3 install wheel
  - sudo pip3 install numpy sympy
  - sudo pip3 install pygsl

script:
  - python3 setup.py install
  - python3 setup.py test
