language: python

sudo: required

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgsl0-dev

install:
  - pip3 install -r requirements.txt
  - pip3 show pygsl
  - dpkg -l libgsl-dev

script:
  - python3 setup.py install
  - python3 setup.py test
